package com.company.Lab_3_1.gui;


import com.company.Lab_3_1.model.Employee;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;
import java.awt.*;

public class TableForm extends Container {
    private JTable staffTable;
    private JPanel tablePanel;
    private StaffTableModel staffTableModel;



    TableForm() {
        staffTableModel = new StaffTableModel();
        staffTable.setModel(staffTableModel);
    }

    public JPanel getTablePanel() {
        return tablePanel;
    }

    public void setData(ArrayList<Employee> db) {
        staffTableModel.setData(db);
    }

    public void refresh() {
        staffTableModel.fireTableDataChanged();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        tablePanel = new JPanel();
        tablePanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        staffTable = new JTable();
        tablePanel.add(staffTable, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return tablePanel;
    }
}
